version: '3'
services:
  postgres:
    image: mdillon/postgis:9.5
    container_name: sprucebot_postgres
    networks:
      - bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: barbershop123
      POSTGRES_USER: barbershopio
      POSTGRES_DB: docker_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: sprucebot_redis
    ports:
      - "6379:6379"
  nginx:
    build: ./docker/nginx/
    container_name: sprucebot_nginx
    networks:
      - bridge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/certs:/etc/nginx/certs
    networks:
      bridge:
        aliases:
          - local-api.sprucebot.com
          - local.sprucebot.com
  api:
    build: ./api/
    privileged: true
    container_name: sprucebot_api
    networks:
      - bridge
    volumes:
      - "./api/app:/src/app"
      - "./api/.babelrc:/src/.babelrc"
      - "./api/.eslintrc:/src/.eslintrc"
      - "./api/.jsbeautifyrc:/src/.jsbeautifyrc"
    environment:
      - SHELL=/bin/bash
    ports:
      - "3005:3005"
      - "4005:4005"
  web:
    build: ./web/
    privileged: true
    container_name: sprucebot_web
    networks:
      - bridge
    volumes:
      - "./web/.eslintignore:/src/.eslintignore"
      - "./web/.eslintrc:/src/.eslintrc"
      - "./web/.babelrc:/src/.babelrc"
      - "./web/.env:/src/.env"
      - "./web/karma.conf.js:/src/karma.conf.js"
      - "./web/server.babel.js:/src/server.babel.js"
      - "./web/tests.webpack.js:/src/tests.webpack.js"
      - "./web/src:/src/src"
      - "./web/bin:/src/bin"
      - "./web/static:/src/static"
      - "./web/webpack:/src/webpack"
    environment:
      - SHELL=/bin/bash
    ports:
      - "3000:3000"
      - "3001:3001"
      - "35729:35729"
    extra_hosts:
      - "local-api.sprucebot.com:10.200.10.1"
networks:
  bridge:
    driver: bridge